### ISSUE TITLE
[Question] Why do we need update even in the cases where loops are not added?

### ISSUE THREAD

**Issue by LimHyungTae** [engcang/FAST-LIO-SAM-QN#10]
I'm wondering why you put the below code outside `if (loop_added_flag_) `

```
{
        std::lock_guard<std::mutex> lock(graph_mutex_);
        isam_handler_->update(gtsam_graph_, init_esti_);
        isam_handler_->update();
        if (loop_added_flag_) 
        {
          isam_handler_->update();
          isam_handler_->update();
          isam_handler_->update();
        }
        gtsam_graph_.resize(0);
        init_esti_.clear();
      }
```

The annotation `//https://github.com/TixiaoShan/LIO-SAM/issues/5#issuecomment-653752936` is relevant to why we need multiple `update()`.

**Comment by engcang** [comment]
Hey @LimHyungTae 

I thought and found `iSAM`  literally, incrementally do SAM.
If we call `update()` and `graph.resize(0)`, `estimate.clear()` only when loop occurs, it should potentially process more updates at loop-closures, whereas it may not, if we already processed earlier updates in the incremental fashion.

What do you think of this?

**Comment by LimHyungTae** [comment]
It seems I asked the an ambiguous question. What I was thinking is why the code isn't be like:

```
{
    std::lock_guard<std::mutex> lock(graph_mutex_);

    if (loop_added_flag_) 
    {
      isam_handler_->update(gtsam_graph_, init_esti_);
      isam_handler_->update();
      isam_handler_->update();
      isam_handler_->update();
      isam_handler_->update();
    }
    gtsam_graph_.resize(0);
    init_esti_.clear();
  }
```

Because once there are no new loops, isam_handler_ does not optimize anything.

**Comment by engcang** [comment]
@LimHyungTae 

First, `gtsam_graph_.resize(0);` and `init_esti_.clear();` should be called only after we call `update`. Otherwise, `graphs` and `init_esti_ values` seem to be just discarded without iSAM update.

So the code should be like either code block 1 or 2:
```cpp
// Code block1
{
    std::lock_guard<std::mutex> lock(graph_mutex_);

    if (loop_added_flag_) 
    {
      isam_handler_->update(gtsam_graph_, init_esti_);
      gtsam_graph_.resize(0);
      init_esti_.clear();
    }
    else // not calling  gtsam_graph_.resize(0); neither init_esti_.clear();
    {
    }
  }


// Code block2
{
    std::lock_guard<std::mutex> lock(graph_mutex_);

    isam_handler_->update(gtsam_graph_, init_esti_);
    gtsam_graph_.resize(0);
    init_esti_.clear();
}
```

So now, it is about the updating only when loop occurs (code block 1), or updating always even without loops (code block 2).
Here I prefer latter. According to the implementation and the characteristics of the iSAM (incremental SAM) as here -https://github.com/borglab/gtsam/blob/develop/gtsam/nonlinear/ISAM2.cpp#L418-L483, it incrementally does SAM by stacking newly input nodes (updating data structures) after linearizing them.

It might be not a big deal to update whole new factors queued till the new loop-closures at once, but I think we can save some time of the thread at loops, by updating the every factors whenever they are input to the iSAM, in advance.

I did not test or analyze this yet, but I just hopefully believe this can help to prevent the threads buffer getting busy or stuck by saving tiny computation times.


Calling multiple times of `update()` is for the faster convergence, as already discussed here - https://github.com/TixiaoShan/LIO-SAM/issues/5#issuecomment-653752936 and explained at official GTSAM's example code - https://github.com/borglab/gtsam/blob/30f4dbb1b80f274bbd9e82a18fb2831110e058f0/examples/VisualISAM2Example.cpp#L126-L131

**Comment by LimHyungTae** [comment]
Wow, such a great answer. I've never known that isam automatically manges new factors like this:

```
update.pushBackFactors(newFactors, &nonlinearFactors_, &linearFactors_,
                         &variableIndex_, &result.newFactorsIndices,
                         &result.keysWithRemovedFactors);
  update.computeUnusedKeys(newFactors, variableIndex_,
                           result.keysWithRemovedFactors, &result.unusedKeys);
```

so I think the current version (i.e., the latter case of the code snippet above) would be fine, and `isam_handler_->update(gtsam_graph_, init_esti_);` would only update the unobserved factors inside them. Thanks!
