### ISSUE TITLE
[Enhancement] Improving the readability and maintainability of the code

### ISSUE THREAD

**Issue by LimHyungTae** [engcang/FAST-LIO-SAM-QN#8]
wanted to share a few suggestions that I believe could help improve the readability and maintainability of the code

These suggestions are based on widely accepted practices and would help make the code easier to follow for both current and future team members.

## 1. Adopting the Google C++ coding style

Especially, I strongly recommend following **Google C++ coding style** for your future collaboration with other guys after graduation (and we can also set an automatic formatting tool, see the `Suggestion` part).

## 2. Move away from the m_ prefix for member variables

I guess you had been affected by Seungwon, but in modern development, the developers avoid using `m_` (the reason for using `m_` is that there were no advanced IDEs and colorful displays in the 20th century.)

Please read this article for clean code: https://medium.com/@saddamhr/mastering-clean-code-principles-the-art-of-naming-variables-and-functions-b8a5643b127f

## 3. Avoid using _ as a suffix for local variables

I’ve noticed the use of _ as a suffix in local variables, and I think removing this would improve clarity. 

It can sometimes cause confusion, especially since there's typically no need to differentiate local variables in this way.

 I suggest following the common convention of using `_` for private member variables, as seen in the Google C++ style guide, and eliminating its use in local variables.

## 4. Avoid One-to-Many-based harder and cpp file configuration.

The current setup of having One-to-Many relationships between headers and source files could complicate the overall design and make it harder to follow object-oriented design principles. 

I believe refactoring these relationships could help make the code more modular and easier to understand.

---

## Suggestion

Regarding issues 1, 2, and 3, those can be easily resolved than you expect! When we have some free time, please read this article and set the `.pre-commit-config.yaml` and `.clang_format` files: 
https://limhyungtae.github.io/2024-10-14-clang-format%EA%B3%BC-pre-commit%EC%9D%84-%ED%86%B5%ED%95%9C-%EC%BD%94%EB%93%9C-%EC%9C%A0%EC%A7%80-%EB%B3%B4%EC%88%98-%EC%89%BD%EA%B2%8C-%ED%95%98%EA%B8%B0/

**Comment by engcang** [comment]
@LimHyungTae 
Looks and sounds all great!

I thought I have been following the Google C++ style as much as possible, sadly without any validation or reviewing, as I usually learned C++ by solely reviewing SOTA algorithms and yes, most from Seungwon's or other seniors' codes.

Thank you for your suggestions and I Googled a lot after reading this issue.
1. Adopting Google C++ style -> Got it. Let me review the Google C++ guide again.
2. Not using m_ in member variables -> Got it. Then, how about using `this` instead, you think? 
For instance,
```cpp
Class ExampleClass
{
private:
  // double m_example_var = 1.0;
  double example_var_ = 1.0;
public:
  // int m_example_int_var = 1;
  int example_int_var = 1; // As public, not using _ at the end?
  void testFunction();
}

void ExampleClass::testFunction()
{
  double example_usage_of_member_variable = this.example_var_ * 2.0;
  int example_usage_of_int_member_variable = this.example_int_var * 3;
  return;
}
```
3. Not using _ in local variables -> Got it. Then should we use _ at the end of private member variables only? How about public variables? Just leave them without any suffixes?
4. OOD-based cpp files configuration -> Got it. You may know that I usually have been terribly coding everything in one hpp file before. After reading some SOTA codes, I decided to separate cpp and h or hpp files and found some SOTA repos separate them based on functionalities of the codes rather than OOD (which are callbacks, constructors, methods, etc, as I did in this repository). Let me look into your latest PR!

By the way, I think we can discuss more in PR's comment. So if you want to answer to few of my questions above, then please kindly reply them here, then I will close this issue and will continue the discussion in the PR.

**Comment by LimHyungTae** [comment]
For sure man, here, I’d like to share my answer to dicuss the better format with you :) 

Regarding 2 & 3: Do we necessarily need to need put global variables? I think, the trend of style is that, just setting `config` struct if you want to need to set global parameters for better representation of globally used parameters. For instance, In the `loop_closure.h` in #9, I set many config struct, which make the separate the class and user-defined parameters. 

On of the benefits of this implementation is that, in the case where you need to add the additional parameters, we don’t need to fix the pre-set pipeline; but what we need is to just add the parameters inside the struct. This is because all the global parameters are managed by as follows:

```
config_ = config // `config` is the input of the class
```

4. Yep, you might feel that it takes lot of time to manage the files in a OOD manner, but I strongly believe that it gonna reduce lots of time to maintenance the code (for instance, once we modularize the codes in this repository, the only thing we need for `FAST-LIO-SAM-SC-QN` is just fixing the `loop_closure.h` and `loop_closure.cpp` to add some feature descriptors and fix the fecthing mechanism.
